version: '2'
services:
    skillsdbrt-app:
        image: skillsdbrt
            - skillsdbrt-mariadb:mariadb
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:3306/skillsdbrt
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    skillsdbrt-mariadb:
        extends:
            file: mariadb.yml
            service: skillsdbrt-mariadb
