version: '2'
services:
    skillsdbrt-mariadb:
        container_name: skillsdbrt-mariadb
        image: mariadb:10.1.17
        # volumes:
        #     - ~/volumes/jhipster/SkillsDBRT/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=skillsdbrt
        ports:
            - 3306:3306
